# Site settings 
title: Greenshot
#email: getgreenshot@gmail.com
description: Greenshot - a free screenshot tool optimized for productivity
baseurl: ""
# TODO change URL to getgreenshot.org
url: https://getgreenshot.org
twitter_username: greenshot_tool
github_username: greenshot
#facebook: Greenshot.Tool
openhub_project: greenshot
repository: "greenshot/greenshot"

metarobots: index,follow

collections:
  faqs:
    output: true
    permalink: /faq/:title/
  posts:
    output: true
    permalink: /:year/:month/:day/:title/ 
  screenshots:
    output: true
    permallink: /screenshots/:title/

defaults:
  scope:
    path: "faq"
    type: "faqs"
  values:
    layout: "faq"

# Build settings
markdown: kramdown
permalink: pretty
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'CNAME', 'LICENSE', '*.sh', '.git']

plugins:
  - jemoji
  - github-pages
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
